services:
  api:
    build:
      context: ./api
    container_name: fast_api
    ports:
      - "8080:80"
    volumes:
      - ./api/app:/code/app
    env_file: ".env"

  redis:
    image: redis:8.4.0-alpine
    ports: 
      - "6379:6379"
  
  # redisinsight:
  #   image: redis/redisinsight:3.0
  #   ports:
  #     - "5540:5540"

  frontend:
    build:
      context: ./frontend
    container_name: vite
    ports:
      - "8081:5173"

